# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
# LoadBalancer for validator service

apiVersion: v1
kind: Service
metadata:
  name: validator-service
spec:
  type: LoadBalancer
  selector:
    app: validator-deployment
  ports:
    - port: 80
      targetPort: 8080

---
# ClusterIP for calculator service

apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: ClusterIP
  selector:
    app: calculator-deployment
  ports:
    - port: 8081
      targetPort: 8081

---
# Deployment Resource for validator service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-deployment
  template:
    metadata:
      labels:
        app: validator-deployment
    spec:
      containers:
        - name: validator-container
          image: us-central1-docker.pkg.dev/k8s-project-id-1/cloud-repository/validator-img:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /Raj_PV_dir/
          imagePullPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage-claim

---
# Deployment Resource for calculator service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-deployment
  template:
    metadata:
      labels:
        app: calculator-deployment
    spec:
      containers:
        - name: calculator-container
          image: us-central1-docker.pkg.dev/k8s-project-id-1/cloud-repository/calculator-img:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: data
              mountPath: /Raj_PV_dir/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage-claim
